// export default {
//     ts: "TypeScript",
//     js: "JavaScript",
//     python: "Python",
//     sqlite: "SQLite",
//     mongo: "MongoDB",
//     postgreSql: "PostgreSQL",
//     html: "HTML",
//     css: "CSS",
//     sass: "SASS",
//     scss: "SCSS",
//     less: "Less",
//     stylus: "Stylus",
//     ejs: "EJS",
//     jinja: "Jinja2",
//     node: "Node.js",
//     vscode: "VSCode",
//     nvim: "NeoVim",
//     figma: "Figma",
//     git: "Git & GitHub",
//     xfce: "XFCE",
//     react: "React",
//     discordJs: "Discord.js",
//     flask: "Flask",
//     quart: "Quart",
//     express: "Express",
//     rtk: "RTK",
//     zod: "Zod",
//     webpack: "WebPack",
//     pug: "Pug",
//     gulp: "Gulp",
//     next: "Next",
//     deno: "Deno",
//     pixijs: "PixiJS",
//     preact: "Preact",
// }

export default {
  c: "C",
  cpp: "C++",
  js: "JavaScript",
  ts: "TypeScript",
  python: "Python",
  sql: "SQL",
  nosql: "NoSQL",
  html: "HTML",
  css: "CSS",
  tailwindcss: "Tailwind CSS",
  sass: "SASS",
  scss: "SCSS",
  less: "Less",
  ejs: "EJS",
  pug: "Pug",
  jinja: "Jinja2",

  mongodb: "MongoDB",
  mysql: "MySQL",
  postgresql: "PostgreSQL",
  sqlite: "SQLite",

  react: "React",
  "react-native": "React Native",
  next: "Next.js",
  express: "Express",
  flask: "Flask",
  quart: "Quart",
  node: "Node.js",
  gulp: "Gulp",

  vscode: "VS Code",
  nvim: "NeoVim",
  figma: "Figma",
  git: "Git",
  github: "GitHub",
  postman: "Postman",

  kafka: "Kafka",
  jwt: "JWT (Auth)",
  cloudinary: "Cloudinary",
  razorpay: "Razorpay",
  phonepe: "PhonePe",
  tailwindcss:"tailwindcss",
  openMap:"openMap",
  

  concept:"concept",
  other_tools:"other_tools:",
  

  "data-structures": "Data Structures",
  "object-oriented-programming": "Object-Oriented Programming",
  "system-design": "System Design",
  dbms: "DBMS",
  networking: "Computer Networking"
};
